<?php
DEFINE('TALLERES', array(
    'RONDALLA',
    'ARTESANIAS',
    'BAILE',
    'EDECAN',
    'FOTOGRAFÍA',
    'CREACIÓN LITERARIA',
    'VÍDEO DOCUMENTAL',
    'AJEDRÉZ',
    'DIBUJO',
    'ÁREAS VERDES',
    'CANTO',
    'PINTURA',
    'RECICLADO',
    'DECLAMACIÓN',
    'FUTBOL',
    'BASQUETBALL',
    'VOLLEYBALL',
));